services:
 db:
   image: postgres:17
   environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 1000tenge
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env
 
 django-web:
   build: .
   container_name: django-docker
   ports:
     - "8000:8000"
   depends_on:
     - db
   environment:
      DJANGO_SECRET_KEY: xl98+tmx5t5mq)!hesp^b_!bwk_bo(*r2icv8hviz)x#l)969x
      DEBUG: True
      DJANGO_LOGLEVEL: info
      DJANGO_ALLOWED_HOSTS: localhost
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1000tenge
      DATABASE_HOST: db
      DATABASE_PORT: 5432
   env_file:
     - .env
volumes:
   postgres_data: