# Generated by Django 5.2 on 2025-05-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Learner', 'Learner'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='Learner', max_length=20),
        ),
    ]
